# Clustering K-Means

In [2]:
# import libraries
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()  # for plot styling
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [34]:
df = pd.read_csv('merged_train.csv', sep = ';', decimal = ',')
df.head()

,customerid,longitude_gps,latitude_gps,edad,bank_account_type_Current,bank_account_type_Other,bank_account_type_Savings,bank_name_clients_Access Bank,bank_name_clients_Diamond Bank,bank_name_clients_EcoBank,...,level_of_education_clients_UNKNOWN,loannumber,loanamount,totaldue,termdays,referredby,good_bad_flag,times_loaned,times_late,times_referred
0,8a858e135cb22031015cbafc76964ebd,3.319219,6.5286039,48,0,0,1,0,0,0,...,1,2,10000.0,13000.0,30,1,1,1.0,0.0,1.0
1,8a858e275c7ea5ec015c82482d7c3996,3.3255983,7.1194033,36,0,0,1,0,0,0,...,1,2,10000.0,13000.0,30,0,0,1.0,1.0,0.0
2,8a858e5b5bd99460015bdc95cd485634,5.7460998,5.5631737,35,0,0,1,0,0,0,...,1,4,10000.0,13000.0,30,0,1,3.0,2.0,0.0
3,8a858efd5ca70688015cabd1f1e94b55,3.3628497,6.6424853,30,0,0,1,0,0,0,...,1,2,10000.0,11500.0,15,0,1,1.0,1.0,0.0
4,8a858ea05a859123015a8892914d15b7,3.365935,6.5648233,31,0,0,1,1,0,0,...,1,6,20000.0,24500.0,30,0,1,5.0,2.0,0.0

In [39]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3277 entries, 0 to 3276
Data columns (total 92 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   customerid                                                                          3277 non-null   object
 1   longitude_gps                                                                       3277 non-null   object
 2   latitude_gps                                                                        3277 non-null   object
 3   edad                                                                                3277 non-null   int64
 4   bank_account_type_Current                                                           3277 non-null   int64
 5   bank_account_type_Other                                                             3277 non-null   int64
 6   bank_account_type_Savings                                                           3277 non-null   int64
 7   bank_name_clients_Access Bank                                                       3277 non-null   int64
 8   bank_name_clients_Diamond Bank                                                      3277 non-null   int64
 9   bank_name_clients_EcoBank                                                           3277 non-null   int64
 10  bank_name_clients_FCMB                                                              3277 non-null   int64
 11  bank_name_clients_Fidelity Bank                                                     3277 non-null   int64
 12  bank_name_clients_First Bank                                                        3277 non-null   int64
 13  bank_name_clients_GT Bank                                                           3277 non-null   int64
 14  bank_name_clients_Heritage Bank                                                     3277 non-null   int64
 15  bank_name_clients_Keystone Bank                                                     3277 non-null   int64
 16  bank_name_clients_Skye Bank                                                         3277 non-null   int64
 17  bank_name_clients_Stanbic IBTC                                                      3277 non-null   int64
 18  bank_name_clients_Standard Chartered                                                3277 non-null   int64
 19  bank_name_clients_Sterling Bank                                                     3277 non-null   int64
 20  bank_name_clients_UBA                                                               3277 non-null   int64
 21  bank_name_clients_Union Bank                                                        3277 non-null   int64
 22  bank_name_clients_Unity Bank                                                        3277 non-null   int64
 23  bank_name_clients_Wema Bank                                                         3277 non-null   int64
 24  bank_name_clients_Zenith Bank                                                       3277 non-null   int64
 25  bank_branch_clients_ IDI - ORO MUSHIN                                               3277 non-null   int64
 26  bank_branch_clients_17, SANUSI FAFUNWA STREET, VICTORIA ISLAND, LAGOS               3277 non-null   int64
 27  bank_branch_clients_40,SAPELE ROAD ,OPPOSITE DUMAZ JUNCTION BENIN CITY EDO STATE.   3277 non-null   int64
 28  bank_branch_clients_47 LAGOS ROAD, IKORODU                                          3277 non-null   int64
 29  bank_branch_clients_ABEOKUTA                                                        3277 non-null   int64
 30  bank_branch_clients_ABULE EGBA                                                      3277 non-null   int64
 31  bank_branch_clients_ABULE EGBA U-TURN,BRANCH                                        3277 non-null   int64
 32  bank_branch_clients_ACCESS BANK PLC, CHALLENGE ROUNDABOUT IBADAN, OYO STATE.        3277 non-null   int64
 33  bank_branch_clients_ADENIRAN OGUNSANYA                                              3277 non-null   int64
 34  bank_branch_clients_ADEOLA HOPEWELL                                                 3277 non-null   int64
 35  bank_branch_clients_AJOSE ADEOGUN                                                   3277 non-null   int64
 36  bank_branch_clients_AKOWONJO                                                        3277 non-null   int64
 37  bank_branch_clients_AKURE BRANCH                                                    3277 non-null   int64
 38  bank_branch_clients_AKUTE                                                           3277 non-null   int64
 39  bank_branch_clients_ALAUSA                                                          3277 non-null   int64
 40  bank_branch_clients_APAPA                                                           3277 non-null   int64
 41  bank_branch_clients_AWOLOWO                                                         3277 non-null   int64
 42  bank_branch_clients_BOSSO ROAD, MINNA                                               3277 non-null   int64
 43  bank_branch_clients_DUGBE, IBADAN                                                   3277 non-null   int64
 44  bank_branch_clients_DUGBE,IBADAN                                                    3277 non-null   int64
 45  bank_branch_clients_GBAGADA                                                         3277 non-null   int64
 46  bank_branch_clients_HEAD OFFICE                                                     3277 non-null   int64
 47  bank_branch_clients_HERITAGE BANK, DUGBE, IBADAN                                    3277 non-null   int64
 48  bank_branch_clients_ILUPEJU                                                         3277 non-null   int64
 49  bank_branch_clients_LADIPO                                                          3277 non-null   int64
 50  bank_branch_clients_LAGOS                                                           3277 non-null   int64
 51  bank_branch_clients_LEKKI EPE                                                       3277 non-null   int64
 52  bank_branch_clients_MAFOLUKU                                                        3277 non-null   int64
 53  bank_branch_clients_MEDICAL ROAD IKEJA                                              3277 non-null   int64
 54  bank_branch_clients_MUSHIN BRANCH                                                   3277 non-null   int64
 55  bank_branch_clients_OAU ILE IFE                                                     3277 non-null   int64
 56  bank_branch_clients_OBA ADEBIMPE                                                    3277 non-null   int64
 57  bank_branch_clients_OBA AKRAN                                                       3277 non-null   int64
 58  bank_branch_clients_OBA AKRAN BERGER PAINT                                          3277 non-null   int64
 59  bank_branch_clients_OBA AKRAN ROAD, IKEJA,                                          3277 non-null   int64
 60  bank_branch_clients_OGBA                                                            3277 non-null   int64
 61  bank_branch_clients_OGUDU, OJOTA                                                    3277 non-null   int64
 62  bank_branch_clients_OJUELEGBA                                                       3277 non-null   int64
 63  bank_branch_clients_OREGUN                                                          3277 non-null   int64
 64  bank_branch_clients_PLOT 999C DANMOLE STREET, ADEOLA ODEKU, VICTORIA ISLAND, LAGOS  3277 non-null   int64
 65  bank_branch_clients_RING ROAD                                                       3277 non-null   int64
 66  bank_branch_clients_STERLING BANK PLC 102, IJU ROAD, IFAKO BRANCH                   3277 non-null   int64
 67  bank_branch_clients_TINCAN                                                          3277 non-null   int64
 68  bank_branch_clients_TRANS AMADI                                                     3277 non-null   int64
 69  bank_branch_clients_UNKNOWN                                                         3277 non-null   int64
 70  bank_branch_clients_WHARF ROAD, APAPA                                               3277 non-null   int64
 71  employment_status_clients_Contract                                                  3277 non-null   int64
 72  employment_status_clients_Permanent                                                 3277 non-null   int64
 73  employment_status_clients_Retired                                                   3277 non-null   int64
 74  employment_status_clients_Self-Employed                                             3277 non-null   int64
 75  employment_status_clients_Student                                                   3277 non-null   int64
 76  employment_status_clients_UNKNOWN                                                   3277 non-null   int64
 77  employment_status_clients_Unemployed                                                3277 non-null   int64
 78  level_of_education_clients_Graduate                                                 3277 non-null   int64
 79  level_of_education_clients_Post-Graduate                                            3277 non-null   int64
 80  level_of_education_clients_Primary                                                  3277 non-null   int64
 81  level_of_education_clients_Secondary                                                3277 non-null   int64
 82  level_of_education_clients_UNKNOWN                                                  3277 non-null   int64
 83  loannumber                                                                          3277 non-null   int64
 84  loanamount                                                                          3277 non-null   object
 85  totaldue                                                                            3277 non-null   object
 86  termdays                                                                            3277 non-null   int64
 87  referredby                                                                          3277 non-null   int64
 88  good_bad_flag                                                                       3277 non-null   int64
 89  times_loaned                                                                        3272 non-null   object
 90  times_late                                                                          3272 non-null   object
 91  times_referred                                                                      3272 non-null   object
dtypes: int64(84), object(8)
memory usage: 2.3+ MB

In [37]:
wss=[]

for i in range (1,11):
    kmeans = KMeans(n_clusters = i, max_iter = 300)
    kmeans.fit(df)
    wcss.append(kmeans.inertia_)

ValueError: could not convert string to float: '8a858e135cb22031015cbafc76964ebd'