In [2]:
get_ipython().system('pip install pandas')
pip install seaborn
pip install matplotlib
pip install pandas_profiling
pip install pathlib
pip install ipywidgets

SyntaxError: invalid syntax (<ipython-input-2-abcd5c636d17>, line 2)

In [1]:
import pandas as pd                    #gestionar dataframes
import numpy as np  
import seaborn as sns
import matplotlib 
from pandas_profiling import ProfileReport
import pathlib
import xgboost as xgb
from xgboost import XGBRegressor
from xgboost import plot_importance
from matplotlib import pyplot
import matplotlib.pyplot as plt
import ipywidgets
import sklearn
get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'pandas_profiling'

In [3]:
df = pd.read_csv(r"https://raw.githubusercontent.com/medinaltbx/G6_DP3/master/data/input/merged_data/train/merged_train.csv", sep=';' , decimal='.')

In [4]:
df.head()

,customerid,edad,bank_account_type_Current,bank_account_type_Other,bank_account_type_Savings,bank_name_clients_Access Bank,bank_name_clients_Diamond Bank,bank_name_clients_EcoBank,bank_name_clients_FCMB,bank_name_clients_Fidelity Bank,...,level_of_education_clients_UNKNOWN,loannumber,loanamount,totaldue,termdays,referredby,good_bad_flag,times_loaned,times_late,times_referred
0,8a858e135cb22031015cbafc76964ebd,48,0,0,1,0,0,0,0,0,...,1,2,10000.0,13000.0,30,1,1,1.0,0.0,1.0
1,8a858e275c7ea5ec015c82482d7c3996,36,0,0,1,0,0,0,0,0,...,1,2,10000.0,13000.0,30,0,0,1.0,1.0,0.0
2,8a858e5b5bd99460015bdc95cd485634,35,0,0,1,0,0,0,0,1,...,1,4,10000.0,13000.0,30,0,1,3.0,2.0,0.0
3,8a858efd5ca70688015cabd1f1e94b55,30,0,0,1,0,0,0,0,0,...,1,2,10000.0,11500.0,15,0,1,1.0,1.0,0.0
4,8a858ea05a859123015a8892914d15b7,31,0,0,1,1,0,0,0,0,...,1,6,20000.0,24500.0,30,0,1,5.0,2.0,0.0